### ISSUE TITLE
Router deployment workflow improvements

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#218]
### Environment
* Python version:  3.6.9
* Peering Manager version: master

### Proposed Functionality

- Deploy to multiple routers at once. Checkboxes next to routers in the router list view, plus a button to deploy. 
- Select all "dirty" routers button (i.e ones that have had changes to their IX - new/altered sessions). This can also help optimize the scheduled deployments as well. 
- Skip config validation during bulk deployment. Report diffs/errors after the completion.
- Job queue for deployment (and possibly other background tasks), potentially allows parallelized deployment/job execution. (optional)

### Use Case
When turning up multiple sessions at once across multiple IX'es on multiple routers, it would be nice to just push all those changes out at once without having to push to every single router. 

### External Dependencies
For the job queue there may be external dependencies to track the job queue, either using Redis or Postgres.

**Comment by respawner** [comment]
If redis could be a fit for queuing deployment tasks that would be great as I plan to use it as caching mechanism as well.

**Comment by mngan** [comment]
Redis can be used as a message queue through the pub/sub mechanism.

**Comment by respawner** [comment]
Implemented in 6660674. It will probably require some fine tuning to make it "perfect".

**Comment by rlanyi** [comment]
I've just tried this but it seems that the background job is not invoked. I'm using a dockerized version of peering-manager v1.2.1 and everything else seems to work fine. Even if I only check one specific router in the list, nothing happens after pressing "Deploy on Selected" and confirming in the dialog. Comparing and deploying configuration for the same router works fine from the web GUI on the `/routers/<id>/configuration/` page.

I've checked all the logs but there are no info related to the task. I've also checked the HTTP response in the browser's developer toolbar when I've pressed the button and the response is `{"status":"success"}` with HTTP 200. So everything seems to be OK here.

Is it possible to turn on debugging somewhere to see the root cause?

**Comment by respawner** [comment]
I am now considering this topic as the next big improvement to work on. While Redis is used a lot for caching right now, it's still not used as much as we could though it would be useful. I'm mostly thinking about people having Peering Manager instances with a lot of data.

Several mechanisms could benefit from using background jobs to avoid WSGI timeouts. It does bring other questions, and one particular comes to my mind: how do we notify users when a job finishes? While we can simply enqueue a task for background processing, I have no clue if the background job will be able to trigger user interface code. A couple of possible solutions come to me: having some JS code performing regular checks or notify an API endpoint at the end of the job.

One more thing to figure out is implementing some kind of job result class to inspect details about a specific job, if it was successful or not. This is something important as users, like @rlanyi, can get stuck wondering why something does not seem to work as intended.

**Comment by gmazoyer** [comment]
I'm considering this issue as solved as we now have job results reported in the user interface as well as the API. Bulk config deployment is also provided starting background jobs that can be reviewed to see how they've run.
