### ISSUE TITLE
New `Connection` model to handle multiple IX connections

### ISSUE THREAD

**Issue by gmazoyer** [peering-manager/peering-manager#246]
Currently if you have 2 or more connections to the same IX you have to create 2 or more IX instances in Peering Manager. It might be interesting to introduce a `Connection` or `Port` or whatever object that would change the game. Instead of having multiple IX instance, you'll have one with multiple `Connection` on it (a connection being, IP addresses to use, as well as other details).

This work could include the fix for #216 as well.

_Originally posted by @respawner in https://github.com/respawner/peering-manager/issues/221#issuecomment-615213571_

**Comment by kzorba** [comment]
Hello,

this seems to be a good proposal. The whole idea is to disassociate the (local) IPv4/IPv6 address in the peering from the Internet-Exchange entity so as to have one-to-many relationship.

Using peering-manager as the source of truth for BGP sessions, I would like to have all necessary information for config generation via the API. Currently, I do not see the local IP address for each peering in

`GET /api/peering/internet-exchange-peering-sessions/`

If possible please add it, to make the information comparable to

`GET /api/peering/direct-peering-sessions/`

With the current status, if we want to generate config for the Internet Exchange peerings we would need to make 2 API calls, instead of one. 
After you introduce the Connection model I would like to have the connection details also via the API for all the Internet Exchanges peering sessions.

Thanks for the good work on this software!
