### ISSUE TITLE
Support for querying multiple objects via the API

### ISSUE THREAD

**Issue by 2bithacker** [peering-manager/peering-manager#293]
### Environment
* Python version:  3.7.6
* Peering Manager version:  master

### Proposed Functionality

An ability to supply multiple arguments via the REST API and potentially return multiple objects without having to query the entire object set and filter locally, or make multiple API calls.

For example, if I want information on two `AutonomousSystem` objects, I'd like to be able to query `/api/peering/autonomous-systems/?asn=X&asn=Y` and have information on both X and Y returned.

I think it'd be useful to make this sort of functionality available across the entire API, not specifically just to autonomous system lookup. This is similar to the functionality described in the [NetBox API Filtering documentation](https://netbox.readthedocs.io/en/stable/rest-api/filtering/).

### Use Case

In my case, we're integrating Peering Manager with our network automation stack and need to get AS information for a set of ASNs. There are enough that we don't want to make individual API requests for each one, so currently we're pulling down the whole list and filtering locally.

### External Dependencies

No new dependencies.

**Comment by respawner** [comment]
I guess that we'll need to turn all filter fields into ones that can accept multiple values (e.g. `SelectMultiple`). And then we need to apply an `OR` logic to return objects matching any of the given values. We do have to make sure that `Tag` lookup will continue to behave as it is right now, `AND` logic.

The tricky part is not the logic itself rather than changing filtersets behaviour dynamically without having to rewrite all of them. Maybe by sub-classing django-filter's `FilterSet` class and changing [`FILTER_FOR_DBFIELD_DEFAULTS`](https://github.com/carltongibson/django-filter/blob/73cb54c4110812f5ea16819ba370948a88f36a53/django_filters/filterset.py#L116) which seems to be doable.
