### ISSUE TITLE
poll_peering_sessions command inefficiency

### ISSUE THREAD

**Issue by rlanyi** [peering-manager/peering-manager#334]
### Environment
* Docker image: `peeringmanager/peering-manager:v1.2.1`
* Python version:  `Python 3.9.0`
* Peering Manager version:  `v1.2.1`

### Steps to Reproduce

* Add a large number of IXPs
* For many of them check the "Poll Peering Session States"
* Add a few ASNs and add IX peering sessions for the checked IXPs above
* Configure the routers for napalm
* In CLI run `python3 manage.py poll_peering_sessions --all`

### Expected Behavior

The command above should connect to all routers and gather BGP session data (via `get_bgp_neighbors`) **exactly once** for each router. Then it should iterate on the IXPs that have "Poll Peering Session States" enabled and match session data with the data from the router that matches the IXP's router and update the database.

### Observed Behavior

The command iterates on the IXPs and connects to the corresponding router to get BGP session data **for each IXP separately** to update data related only to that IXP. Because there are much more IXPs than routers and because of the relatively slow napalm tasks (can be almost a minute) this results in a very long operation.

### Additional notes

Another solution would be to cache the data from the routers and when a router would be contacted for the second time then use the cached value instead of reconnecting to the router again. The cache could be dropped when the command exits. With this the "iteration logic" would not change.

**Comment by gmazoyer** [comment]
I have several things in mind to address here:

1. I feel like polling sessions is a bit confusing. In the current state, PM is polling sessions based on IXP and BGP group flags. Maybe this is not right. We could move this little flag (the checkbox in forms) in the router instead. In this way, users could exclude some routers from the polling process.
2. I fully agree with the inefficiency of the process and fixing it will require an important rewrite of it, splitting complex logics into smaller parts. Instead of going IXP by IXP and group by group, we need to figure out the routers to poll and go router by router instead.
3. Caching can be a good idea to avoid to heavy load though it is a bit more complex to implement and it will probably (I'm pretty sure about it actually) comes with bugs.

I'd like to have some feedbacks on my first point before starting rewriting the polling mechanism.

**Comment by mngan** [comment]
Agree with respect to polling by router rather than by IXP. Polling by IXP/BGP Group can still be achieved without changing the by router approach by filtering the routers by IXP Connection and BGP Group Association. Then only updating the sessions that are associated with the IXP/BGP groups requested. (or you could just update all IXP/BGP groups associated with the router since you already spent the time fetching them).
