### ISSUE TITLE
IXP page crashing due to missing local AS

### ISSUE THREAD

**Issue by altf4arnold** [peering-manager/peering-manager#335]
### Environment
* Python version:  3.7.3
* Peering Manager version: 1.3.0

### Steps to Reproduce
When I'm opening the page of an IXP, it's crashing

### Expected Behavior
Showing the IXP page
### Observed Behavior
Getting this error message :
```
              <class 'AttributeError'>
              

              'NoneType' object has no attribute 'get_absolute_url'
              

              Python version: 3.7.3
              Peering Manager version: v1.3.1-dev
```

**Comment by altf4arnold** [comment]
Problem residing because the affiliate AS didn't existed and wasn't linked to the IXP's.

**Comment by respawner** [comment]
The issue seems to come from the migration process itself. After moving to `1.3.0` an affiliated AS should have been created and set as local AS for existing objects (IX, routers, …). This process seems to have failed for some reason. We should investigate and fix it to avoid more users to hit the same issue.
