### ISSUE TITLE
Check that local and remote IP belongs to the same subnet

### ISSUE THREAD

**Issue by gmazoyer** [peering-manager/peering-manager#358]
### Environment

* Python version:  3.8
* Peering Manager version:  main

### Proposed Functionality

Check that the local IP and the remote IP for a direct peering session belongs in the same subnet.

### Use Case

This check will avoid typo in either one of the IP by preventing users to create a new session if the IPs are not in the same subnet. It could also make sense to look at the multi hop TTL field. If it is set to `1` then the IPs must belong to the same subnet, otherwise in case of multi hop base sessions the IPs can be in different subnets.

### External Dependencies

None

**Comment by respawner** [comment]
Need to move from `InetAddressField` to `CidrAddressField` to include mask length. The migration must also transform the value when upgrading.

**Comment by jamesditrapani** [comment]
@gmazoyer Would you say the best way to achieve this is to use a custom Django validator on the `ip_address` field of a`BGPSession`?

**Comment by gmazoyer** [comment]
It probably cannot be addressed in a validator.

Firstly, the direct session model needs to be subnet aware, meaning we need to allow people to use a CIDR notation in the field (hence mentioning `CidrAddressField` above). This change have to be seamless for the users, so we will need for each individual direct session to guess, as best as we can, what could be the most precise mask length for IP addresses.

Secondly, we need to correlate the `local_ip_address` field with the `ip_address` field, knowing that `local_ip_address` field is optional in direct session, so we need to watch for `NULL` values. This work is most fitted for the `clean()` method of the `DirectPeeringSessionForm`.

**Comment by maznu** [comment]
I think at https://github.com/peering-manager/peering-manager/commit/27b9c5f289b6881f80c787ab2c452206476c2a5d doesn't address everything in the original report — I don't know if this was intentional or not.

If I specify multihop>=2, and try to create a peering with two different IPs not in the same subnet, I get the same error:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/9492487/158691716-93eb0f41-c220-4b9f-b9d1-6b20de883202.png">

Of course, we're trying to use Peering Manager for iBGP (which is inherently multihop) as well as eBGP — but the point still stands.

Would you like me to raise two issues?

1. *eBGP bug*: if `$hops` > 1 then skip same-prefix validation
2. *iBGP feature*: following on from (1), or if `$local_asn` == `$remote_asn` then skip same-prefix validation

I'm happy to submit PRs for each.

Thanks!

**Comment by gmazoyer** [comment]
Good point. This is something that I forgot when adding the subnet check. You may create a single issue to fix these two cases.
