### ISSUE TITLE
Policies with the wrong family can be assigned to a BGP Session

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#451]
### Environment

* Python version:  3.8
* Peering Manager version:  1.4.2

### Steps to Reproduce

1. Create an IPv6 policy
2. Create an IPv4 Session and add the IPv6 policy to it
3. View the IPv4 Session
4. Render router template

### Expected Behavior

Not sure what the right thing to do here is. Possible options

* Filter the allowable policies in the UI to the family of the IP in the session (may not know that information at the time the autocomplete is triggered)
* Sanity check at submission time to see if policies match the family of the session (error? silently drop the policy?)
* When retrieving the list of policies, exclude the mismatched policies (could lead to invisible policies that cannot be disassociated). 

### Observed Behavior

* The autocomplete will list all policies that match the import/export filter, but will also include both IPv4 and IPv6 policies
* Submitting a mismatched policy will be accepted
* Viewing the policies for a session will return the mismatched policy
* Rendering a template with `session | iter_export_policies` or `session | merged_export_policies` will include the mismatched policy associated with the session.

**Comment by gmazoyer** [comment]
I agree that we should try to filter applicable policies to a BGP session based on the address family. That said, there are 2 different issues to address.

1. Hard one, only show applicable policies to the users in the selection list. It's complicated because the filter to retrieve the list items is built on form rendering. This means that when creating the session we have to re-generate the filter based on the address family of the IP that the user just wrote. So we need to listen on the IP address field, raising an event when the user finishes typing, that will then adjust the filter of the select2 widget. TL;DR it's hard to do right now.
2. Easy one, when the user validate the form we should make sure that policies are consistent given the address family of the IP and the ones from the policies. If it is not coherent, say IPv6 address with IPv4 policies, we can raise an error on form validation.

**Comment by gmazoyer** [comment]
Point number 2 addressed in af2f355.
