### ISSUE TITLE
BGP community type

### ISSUE THREAD

**Issue by Paktosan** [peering-manager/peering-manager#479]
Some router platforms have different configuration sections for standard, extended or large communities, so we have to differentiate between them when generating a configuration in Peering Manager.
While it is possible to use tags for this, it is not a very elegant solution.
As discussed on Slack, I would propose to automatically detect the community type and make it available as a property so it can be used in templating.

**Comment by gmazoyer** [comment]
I've been thinking about this and maybe the best way to bring this feature is to add a field for it with a value for the user to select. Vendors are using different notations and it will come with pain if we have to parse these notations to determine the community type.

Second point if we were to add that field, we already have one called `type` to mention when the community is applied. Should we rename that field? I also started a [discussion ](https://github.com/peering-manager/peering-manager/discussions/577)a few weeks back to propose deprecating it, but it looks like we'll keep it as optional.

**Comment by wtremmel** [comment]
Hmm, IMHO the community type is implicit - you enter a community and because regular, extended and large communities are syntactically very different you see what type it is.

Alternatively, let the user select what they want, but then implement a strict syntax check that only valid communities of that type can be entered.
