### ISSUE TITLE
extending config contexts

### ISSUE THREAD

**Issue by maznu** [peering-manager/peering-manager#567]
### Peering Manager version

v1.6.0

### Feature type

New functionality

### Proposed functionality

I intend to submit a PR to address some of what is discussed in https://github.com/peering-manager/peering-manager/discussions/505#discussioncomment-2303287

In essence, I would be adding `config_context` (and associated views and API serialisation) to the following models:

* `peering.models.AutonomousSystem` — e.g. I am a provide to an AS where it is not appropriate for our import prefix-list to be based solely on what's in PeeringDB or IRR data (e.g. maybe they are leasing a /27 from us, and I want our routers to accept those announcements from them)
* `peering.models.BGPGroup` — e.g. I want a group for peers that are "long-lined" to the IX, so down-pref their routes
* `peering.models.DirectPeeringSession` — e.g. downstream customer is using a MikroTik and so I should have more forgiving BGP timers; currently there is nowhere to store BGP timers (or other more specific preferences) within Peering Manager, but config_context can become the kitchen sink?
* `peering.models.InternetExchangePeeringSession` — 
* `peering.models.InternetExchange`
* `bgp.models.Relationship` — e.g. this BGP session is for the PE-CE of an MPLS L3VPN, and we want some values that our template code can use to differentiate this from customer/provider/peer relationships

### Use case

Other things I considered as alternatives to putting `config_context` everywhere:

* using tags — I could special-case in my configs for "if tagged with MikroTik then have longer timers" but now I end up with arbitrary constants in my template code, rather than it being defined in "config" (i.e. data in peering manager)

* using peer-group — again in template code you could have `if peer_group == "long-line-ix-peer"` … `set local-pref 1` but that will break if someone changes the name of a peer group without changing the template; poor separation of config/constants and code

* add more fields to Peering Manager — I think every vendor implementation agrees on certain basics (default originate #566, timers, etc), but what is the "strategy" for Peering Manager? Which common BGP session parameters should have separate fields in models? And which should end up in the "kitchen sink" of `config_context`?

### Database changes

Several instances of `config_context = models.JSONField(blank=True, null=True)` being added, plus views and API additions to accompany them.

### External dependencies

None.

I am happy to submit a PR (or series of PRs) with these developments.

**Comment by gmazoyer** [comment]
I'd like to be extra careful when implementing this. It feels easy to implement I know, just add the config context field to the object we need and we are done. But I have the feeling that this will lead to a number of copy/paste actions to have the same bit of config context on several objects.

That's why we started #505 to discuss the ways we could implement config contexts for more objects. Keep it as a simple field? Add a new config context object that can be assigned to a type of objects (e.g. I want this config context to be applied for all IXPs)? Add a config context object and allow it to be assigned per-object using generic foreign key? Keep a config context field so it can override config context defined at upper level?

We need to answer these questions before writing code as I don't want to create too many migrations to keep the database schema aligned with our ideas.

**Comment by maznu** [comment]
Yes, I agree there is potential for lots of copypasta between objects, and could also mean that config contexts are very large.

> Add a config context object and allow it to be assigned per-object using generic foreign key?

Your idea has the benefit of making a more "composable" context.  I've added some thoughts about this in #505.  In it I suggest one option could be extending the generic foreign keyable object that Peering Manager already has: the Tag.
