### ISSUE TITLE
rqworker container is broken in latest release

### ISSUE THREAD

**Issue by forkwhilefork** [peering-manager/peering-manager#725]
### Peering Manager version

v1.7.4

### Python version

3.9

### Steps to Reproduce

1. Clone docker repository
2. start docker compose

### Expected Behavior

containers should come up

### Observed Behavior

rqworker container fails with an error and exits. This is due to the same issue described here: netbox-community/netbox/#12415

Basically, there is an incompatibility between rq version 1.14.0 and django-rq version 2.8.1 (and earlier). In order to avoid this, we can pin rq to 1.13.0. I will open a PR for this.

**Comment by forkwhilefork** [comment]
this is fixed in 4ae8152502176e95c8f85875dfc86f3918eff8fd but not released yet.

**Comment by gmazoyer** [comment]
Closing as it's been fixed. Thanks for pointing it out though!

**Comment by paketb0te** [comment]
@gmazoyer we are running into the same issue - seeing that it is a rather simple fix, and is already implemented, do you think there is value in providing a minor release?

As of now, installations with the latest release should be broken, as far as I can tell.

(because `django-rq v2.6.0`, as specified in the `requirements.txt` for `peering-manager v1.7.4`. uses `use_connection()` which is deprecated in the newer versions of `rq` (on which `django-rq` obviously depends)).

Might make sense to pin the versions of sub-dependencies as well :thinking:

**Comment by gmazoyer** [comment]
I fixed it in the official Docker image by pinning the `django-rq` version to `2.8.0`. If you use Docker that should be OK. If you don't I recommend using a `local_requirements.txt` with the following line: `django-rq==2.8.0`.
