### ISSUE TITLE
BGPQ3 no longer generates prefixes for many ASNs due to RADB removal from BGPQ3_SOURCES

### ISSUE THREAD

**Issue by falz** [peering-manager/peering-manager#766]
### Peering Manager version

v1.8.1

### Python version

3.8

### Steps to Reproduce

Using a test peer - AS714 (apple) try to get prefixes using `manage.py grab_prefixes` - none will return

```
 prefixes for autonomous systems
  - AS42:
        71 ipv6
       106 ipv4
  - AS714:
         0 ipv6
         0 ipv4
```

Edit config file to add RADB back in, which was removed in https://github.com/peering-manager/peering-manager/issues/745, and it will work.

```
#BGPQ3_SOURCES = 'RPKI,RIPE,ARIN,APNIC,AFRINIC,LACNIC'
BGPQ3_SOURCES = 'RPKI,RIPE,ARIN,APNIC,AFRINIC,LACNIC,RADB'
```

### Expected Behavior

See prefixes from AS714 as well as many others that exclusively use RADB.

### Observed Behavior

We upgraded to 1.8.x with this change and noticed that many AS's no longer had prefxes. The fix was adding RADB back in,. 

RADB is the original IRR sourc, which is used exclusively by many organization (including ourselves). We're in the Research and Education community, and have legacy IP space. There are many like us, who do not have RADB availabe in their local RIR (such as ARIN) database since these are legacy resources.

One can test with bgpq3 directly using  AS714 (apple) to replicate

Without RADB:
```
bgpq3 -h rr.ntt.net AS714 -S RPKI,RIPE,ARIN,APNIC,AFRINIC,LACNIC,ARIN
no ip prefix-list NN
! generated prefix-list NN is empty
ip prefix-list NN deny 0.0.0.0/0
```

With RADB:
```
bgpq3 -h rr.ntt.net AS714 -S RPKI,RIPE,ARIN,APNIC,AFRINIC,LACNIC,ARIN,RADB
ip prefix-list NN permit 17.0.0.0/8
ip prefix-list NN permit 17.0.0.0/9
ip prefix-list NN permit 17.0.0.0/21
ip prefix-list NN permit 17.0.64.0/18
ip prefix-list NN permit 17.0.71.0/24
.. <redacted>
```

I would advocate to add RADB back in by default, I doubt this feature is useful without RADB included, even though this breaks the concept of clenliness in https://github.com/peering-manager/peering-manager/issues/745,

**Comment by falz** [comment]
A few more bits of data:

IRR explorer showing where AS714 has IRR objects (RADB)
* https://irrexplorer.nlnog.net/asn/AS714

RADB wiki page, which goes into some background of it

* https://en.wikipedia.org/wiki/Routing_Assets_Database

**Comment by gmazoyer** [comment]
I understand RADB has been in use for a long time due to gaps in authoritative IRR in some regions. While I'm not a fan of making an exception, especially after opening an issue and discussing it on Slack, if people really wants to reinstate RADB in the default list, we could do it. However opens the door for other exceptions, e.g. someone might want to reinstate ALTDB or other IRR in the default list.

My other proposition would be to document this properly and tell people that if they need RADB, they can change the config. I guess that a lot of people will most likely end up adding RADB to the list. But if we want things to change and authoritative IRR to do their jobs properly we need sometime to show the way.

Although I may have a bias regarding this, managing mostly prefixes in the RIPE region (where IRR seems much more easy and clean) since I've been in the industry.

Please comment on this issue, so I can have people's opinions and act accordingly.

**Comment by tangledhelix** [comment]
_Disclaimer/disclosure: I am one of the operators of rr.ntt.net / NTTCOM. The below is my personal statement, and is NOT a statement on behalf of NTT._

In #745, Stavros K's proposal at RIPE86 is cited as a reason to modify the source list, limiting only to the RIRs. But also in that proposal, a number of sources were given a grace period of 1 year, to account for migration of data.

* RADB
* RIPE-NONAUTH
* NTTCOM
* LEVEL3

My feedback is that the change in #745 may have been premature. The proposal granted a grace period to these specific registries for a reason, which is to avoid the type of disruption that is described by the OP. Stavros' proposal was given in May of this year; even if we assume the clock started ticking on that day, around 8 months of that year still remains.

I recognize your concern about e.g., ALTDB. But one could point to the proposal's grace period slides and make it a matter of project policy that the exceptions are limited to the four databases mentioned specifically. And a schedule could be set for their later removal, if so desired, and that schedule could be prominently placed in README, etc.

**Comment by forkwhilefork** [comment]
IMO this should be user-configurable in the UI. There is no reason for it to be hard-coded (even if a user can go edit the file). I completely agree that relying on authoritative IRRs is a good thing, but the reality is that we as a community just aren't there yet, and even if we were, as someone noted above there's lots of legacy space out there.

I think more-secure defaults are advisable, but I also think it's good to lower the friction to include non-authoritative sources, since many users will need/want to do it.

As a stretch goal, it might be nice to be able to set this per-peer, so that some peers can benefit from the added security even if others can't (but that's a separate issue/feature request).

**Comment by gmazoyer** [comment]
> IMO this should be user-configurable in the UI. There is no reason for it to be hard-coded (even if a user can go edit the file). I completely agree that relying on authoritative IRRs is a good thing, but the reality is that we as a community just aren't there yet, and even if we were, as someone noted above there's lots of legacy space out there.

This has never been hardcoded and still is not. We are talking about the default of a configuration parameter. The parameter can be changed in the `configuration.py` file which all users must have anyway.

**Comment by forkwhilefork** [comment]
Regardless of what you call it, my point is that making a user edit a file to change this parameter is too much friction for something that many people (probably almost everyone) will want to change and that should be a usable default anyway.

I also think it's worth noting that this config file is not very intuitive. At first glance it looks like part of the code (since there are functions at the top), and the way to change a config value is to override the "default value" parameter to `os.environ.get()`.

I reiterate that this should be easily set in the GUI.

**Comment by gmazoyer** [comment]
> Regardless of what you call it, my point is that making a user edit a file to change this parameter is too much friction for something that many people (probably almost everyone) will want to change and that should be a usable default anyway.

Question is what defaults do we set for the value. If we open the door for the RADB exception, which is something I can get, are there other IRRs to include.

> I also think it's worth noting that this config file is not very intuitive. At first glance it looks like part of the code (since there are functions at the top), and the way to change a config value is to override the "default value" parameter to `os.environ.get()`.

Not sure we are talking about the same file here. `configuration.py` is not provided by default and it's up to the user to write it. You probably are talking about the file used by the docker image.

> I reiterate that this should be easily set in the GUI.

That would mean create a wrapper around the configuration of Peering Manager, which is a larger topic to address.

**Comment by forkwhilefork** [comment]
> You probably are talking about the file used by the docker image.

I guess? It's the only one I see (and yes I am using docker).
```
/opt/peeringmanager# find . -name configuration.py
./configuration/configuration.py
```

Is this different from the non-docker version? I was not expecting the configuration to be meaningfully different between docker and non-docker.

I suppose this is getting off-topic. Anyway - to answer your question about the defaults; it's common to have records in RADB and ALTDB (some people see ALTDB as somehow less reputable, which I've never understood). I believe TC, while not itself being authoritative, only allows entries that agree with the Brazilian NIC. It was included in irrexplorer as such: https://github.com/NLNOG/irrexplorer/issues/64

The ISP-specific ones have very few records (those that are still operated). So I think it's safe to exclude them.

So my final answer would be: `RPKI,RIPE,ARIN,APNIC,AFRINIC,LACNIC,TC,RADB,ALTDB`

**Comment by gmazoyer** [comment]
Let's move forward this one. We will re-introduce RADB, ALTDB, RIPE-NONAUTH, NTTCOM, LEVEL3 and TC.
