### ISSUE TITLE
Delete from config when peering session is deleted

### ISSUE THREAD

**Issue by jlixfeld** [peering-manager/peering-manager#86]
### Environment
* Python version:  3.5.3
* Peering Manager version:  master

### Proposed Functionality

- Make `Delete Selected` and `Edit Selected` also available from `ix-peering-sessions`
- Peering sessions that have been deleted from `ix-peering-sessions` or `peering-sessions` should be accessible via slug so they can be added to the deployment templates so the configurations will be deleted from the router.
- Peering Session comments should be merged into autonomous system comments if a peering session is deleted.

### Use Case

Self explanatory? :)

### External Dependencies

- What if a session is deleted and the deploy that would have removed the configuration fails for whatever reason?  Will a subsequent deploy still delete the session even though technically the session was already deleted?

**Comment by respawner** [comment]
Peering sessions removal is currently done based on templates. That said I only worked with Juniper hardware for this, and the `replace:` configuration stanza ensures that the configuration matches exactly what we want. Meaning if sessions are removed from Peering Manager then a Juniper template using `replace:` will make sure they are removed from the configuration as well.

How should we handle peering session removal cases when a network OS does not provide the previously mentioned mechanism? One idea coming immediately to me, is to mark sessions as deleted (not showing them in the UI too) but not really remove them from the database. Or maybe something like a "Recycle Bin" for sessions waiting to be removed from the configuration too.

**Comment by jlixfeld** [comment]
I think the recycle bin idea is a good one.  That would cover IX peering sessions as well as direct peering sessions.

So then the idea is if a session is in the recycle bin, it's accessible by a slug allowing non-Juniper (or even Juniper if they wanted to) devices to use `no neighbor ${slug}` or `delete protocol bgp group blah neighbor ${slug}` or whatever the OS required to delete the session?

And then once the recycle bin is empty, those sessions are no longer accessible by the slug?

**Comment by jlixfeld** [comment]
I was giving this some more thought and I think with the newly committed irr prefix filter generation feature, hooks will need to be present here to delete policy configuration in addition to bgp configuration.

I guess this might be trivial if the deleted entry is marked accordingly in the database (recycle bin) and is accessible by a slug somehow?

**Comment by jlixfeld** [comment]
I was thinking even more about this and there are lots of things that need to be deleted besides the session itself:  Any policy objects created for that session; prefix-lists, firewall filters, route maps, route policies, community lists, etc, etc.

**Comment by respawner** [comment]
This is a really tricky issue. Doing all the cleanup after deleting a session, an IX or even a BGP group can get quite complexe and lead to mistakes. This raises a compliance case to handle, eg "if IX is present, this policies should be present, but not otherwise".

I still need to figure out a way of doing that.

**Comment by bcavns01** [comment]
What could prove valuable would be an api endpoint that would allow a user to get a fully rendered config template.  This would allow someone to, for example, generate almost their full switch config using whatever means they choose, but then insert the output from PeeringManager to handle the peering related sections.  They'd then be able to delete whole policies, communities, etc, and simply let things be rebuilt.

**Comment by respawner** [comment]
@bcavns01 The endpoint you are refering to already exist at `/api/router/{id}/configuration/`. Your idea would work though but not for all cases I guess.

To solve this issue properly, we need to create some kind of relationship between models to know how to cascade deletion inside the config based on dependencies. We also need to add a state for peering session to be marked as "to be decommissioned" and then raise an event deleting this sessions once a configuration pushed to a device.

**Comment by bcavns01** [comment]
Oh, interesting.  I didn't see that while navigating around the rest api, and I get a "page not found", but it looks like `http://<host>/routers/1/configuration/?raw` has what I was looking for. :)

Keeping track of all that state and all the config relationships is painful.

My suggestion wasn't so much solving the problem as shifting the burden to the user for those that really want/need it.   We generate almost full configs for our switches, so we side-step the messy issue of cascading clean-up by just throwing everything out.  Admittedly, this is a more JUNOS-friendly solution.  In our case, we can build our config and then grab only what we need from PeeringManager.  It's more of a convenience since we could just reach into the PeeringManager DB to get what we need to generate things ourselves.

**Comment by gmazoyer** [comment]
Tracking in #301

**Comment by falz** [comment]
Found issue https://github.com/peering-manager/peering-manager/issues/301 and then this one.

Captain obvious - but since v 1.8.0 added more statuses:

https://peering-manager.readthedocs.io/en/stable/release-notes/version-1.8/#status-for-sessions-group-and-devices-735

> Possible statuses are now: requested, provisioning, enabled, pre-maintenance, maintenance, post-maintenance, disabled, decommissioning, and decommissioned.

one can use those in the template to help handle IOS/EOS type of devices. An example would be when a peer is in "decommissioning" state, modify the Jinja template to remove/delete things, push config, then set it to another status such as "decommissioned" (or just delete it) and tell the template to not generate the config at all in that status
